### PR TITLE
refs #1: create rootless images

### LINKED ISSUE #1: Create rootless images

### PR DESCRIPTION
**Pull request by Monska85**
Closes #1

### CODE REVIEW

**Comment by paolomainardi** [comment]
I tried the `bitnami/nginx` image (which is the base image of the nginx helm chart https://artifacthub.io/packages/helm/bitnami/nginx)
and i found an interesting point on how they use user/groups:

```bash
❯ docker run -d bitnami/nginx
1600b9e74f1fb520ffb698133fd78e444dbd8c6a9d2eb7a9a5ac4a065dfab2ff

❯ docker exec -it 1600 id -u
1001

❯ docker exec -it 1600 id -g
0
```

Do you have any idea on how this is a security best practice ? I found this: https://unix.stackexchange.com/questions/44077/what-does-it-mean-to-be-in-group-0

**Comment by Monska85** [comment]
> I tried the `bitnami/nginx` image (which is the base image of the nginx helm chart https://artifacthub.io/packages/helm/bitnami/nginx)
> and i found an interesting point on how they use user/groups:
> 
> ```shell
> ❯ docker run -d bitnami/nginx
> 1600b9e74f1fb520ffb698133fd78e444dbd8c6a9d2eb7a9a5ac4a065dfab2ff
> 
> ❯ docker exec -it 1600 id -u
> 1001
> 
> ❯ docker exec -it 1600 id -g
> 0
> ```
> 
> Do you have any idea on how this is a security best practice ? I found this: https://unix.stackexchange.com/questions/44077/what-does-it-mean-to-be-in-group-0

I have checked this configuration. What I found is that `user 1001` does not exist in the container, so it uses the `other` permissions. I am not really sure if this is a good best practice. The group of the logged in user is `0`, which is the `root` group, and I think this could grant some unwanted privileges. I will check if this approach could improve the security in any way.

**Comment by Monska85** [comment]
I found [this link](https://github.com/bitnami/bitnami-docker-postgresql/issues/103#issuecomment-451887371) which explains why they use this approach. I am not sure that this behaviour is what we want at the moment, but maybe is something that we can add as an option to be compatible with OpenShift also.

**Comment by Monska85** [comment]
> I tried the `bitnami/nginx` image (which is the base image of the nginx helm chart https://artifacthub.io/packages/helm/bitnami/nginx)
> and i found an interesting point on how they use user/groups:
> 
> ```shell
> ❯ docker run -d bitnami/nginx
> 1600b9e74f1fb520ffb698133fd78e444dbd8c6a9d2eb7a9a5ac4a065dfab2ff
> 
> ❯ docker exec -it 1600 id -u
> 1001
> 
> ❯ docker exec -it 1600 id -g
> 0
> ```
> 
> Do you have any idea on how this is a security best practice ? I found this: https://unix.stackexchange.com/questions/44077/what-does-it-mean-to-be-in-group-0

**Review by juanebarreira — APPROVED** [review]

**Comment by paolomainardi** [comment]
@Monska85 la chiudo per adesso

**Pull request closed without merging**
